### ISSUE TITLE
Script to change currently equipped weapon or inventory item.

### ISSUE THREAD

**Issue by tabg-deserves-better-devs** [cripser/TABG_HACK#2]
In TABG there is a LOT of unused/cut items that were available before the beta 13 update, without much reason given. Taser flintlock, hubert the fish, shields, old spells, etc. There is no public script available to spawn/bring these items back in, though there is several paid for or private alternatives. 

A script to change your currently equipped item, or an item in your inventory to something else would be interesting. TABG is on it's last leg and will probably lose support by the end of this year. Any way to give it more content that it deserves would be great. While this could potentially be abused, this game is already being beaten to death with FPS issues, malicious cheaters, desync, etc. It could still be used in a good way, to share old removed content with long time players or just close friends to enjoy again.

**Comment by NoBoat9** [comment]
On god you should add esp and other features i would pay for that

**Comment by cripser** [comment]
> On god you should add esp and other features i would pay for that

then pay
